{% set version = "0.5.0" %}

package:
  name: check-wheel-contents
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/check-wheel-contents/check-wheel-contents-{{ version }}.tar.gz
  sha256: e4a8c1c3ab452ae3d3f4293c3e3a20468461a2ba6fc8f99280b39c146e6f4e3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  number: 0
  entry_points:
    - check-wheel-contents = check_wheel_contents.__main__:main

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=46.4.0
  run:
    - attrs >=18.1
    - click >=7.0
    - packaging
    - pydantic >=1.7,<2.dev0
    - python >=3.8
    - tomli >=1.2,<3.0
    - wheel-filename >=1.1,<2.dev0

test:
  source_files:
    - test
  imports:
    - check_wheel_contents
  commands:
    - pip check
    - check-wheel-contents --version
    - check-wheel-contents --help
    - check-wheel-contents --version | grep -iE "{{ version.replace('.', '\.') }}"
    - pytest -vv --color=yes --tb=long --cov=check_wheel_contents --cov-report=term-missing:skip-covered --no-cov-on-fail -k "not from_local_tree" --cov-fail-under=99
  requires:
    - m2-grep  # [win]
    - pip
    - pytest-cov
    - pytest-mock

about:
  home: https://github.com/jwodder/check-wheel-contents
  summary: Check your wheels have the right contents
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
